import 'package:shared_preferences/shared_preferences.dart';

/// Persistent queue for memories that were saved locally but could not be
/// uploaded at the time they were created.
///
/// IDs are the local memory IDs generated by [Memory]. Keeping this queue
/// separate from the memory model lets the UI treat local persistence and
/// server synchronization as two independent concerns.
final class PendingMemorySync {
  static const _storageKey = 'ben_pending_memory_sync_ids';

  Future<Set<String>> ids() async {
    final prefs = await SharedPreferences.getInstance();
    return (prefs.getStringList(_storageKey) ?? const <String>[]).toSet();
  }

  Future<void> add(String memoryId) async {
    final prefs = await SharedPreferences.getInstance();
    final current = (prefs.getStringList(_storageKey) ?? const <String>[]).toSet();
    current.add(memoryId);
    await prefs.setStringList(_storageKey, current.toList());
  }

  Future<void> remove(String memoryId) async {
    final prefs = await SharedPreferences.getInstance();
    final current = (prefs.getStringList(_storageKey) ?? const <String>[]).toSet();
    if (!current.remove(memoryId)) return;
    await prefs.setStringList(_storageKey, current.toList());
  }
}
